set_property PACKAGE_PIN W5 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
create_clock -add -name sys_clk_pin -period 10.00 [get_ports clock]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clock_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports resetButton]
set_property PACKAGE_PIN U18 [get_ports resetButton]

set_property PACKAGE_PIN U16 [get_ports {fpga_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {fpga_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {fpga_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {fpga_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {fpga_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {fpga_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {fpga_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {fpga_out[7]}]
set_property PACKAGE_PIN V13 [get_ports {fpga_out[8]}]
set_property PACKAGE_PIN V3 [get_ports {fpga_out[9]}]
set_property PACKAGE_PIN W3 [get_ports {fpga_out[10]}]
set_property PACKAGE_PIN U3 [get_ports {fpga_out[11]}]
set_property PACKAGE_PIN P3 [get_ports {fpga_out[12]}]
set_property PACKAGE_PIN N3 [get_ports {fpga_out[13]}]
set_property PACKAGE_PIN P1 [get_ports {fpga_out[14]}]
set_property PACKAGE_PIN L1 [get_ports {fpga_out[15]}]


set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fpga_out[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fpga_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_out[15]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]